version: 2

test:
  override:
    - (cd codalab && py.test)

jobs:
  build:
    environment:
      DJANGO_SETTINGS_MODULE: codalab.settings
      DJANGO_CONFIGURATION: Dev
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: codalab-{{ .Branch }}-{{ checksum "codalab/requirements/requirements.txt" }}
      - run:
          name: CHOWN Python Library Dirs
          command: sudo chown -R $(whoami) /usr/local/
      - run:
          name: Install Memcached reqs
          command: sudo apt-get update --allow-releaseinfo-change && sudo apt-get install libmemcached-dev --fix-missing
      - run:
          name: PIP Install Requirements
          command: pip install -r codalab/requirements/requirements.txt
      - save_cache:
          key: codalab-{{ .Branch }}-{{ checksum "codalab/requirements/requirements.txt" }}
          paths:
            - "~/.cache/pip"
      - run:
          name: Copy settings
          command: cp .circleci/circlec_dev_setup.py codalab/codalab/settings/local.py
      - run:
          name: Run PyTest
          environment:
            DJANGO_SETTINGS_MODULE: "codalab.settings.local"
            DJANGO_CONFIGURATION: "Test"
            CHAHUB_API_URL: "http://localhost/test/"
            CHAHUB_API_KEY: "some-secret-key"
          command: cd codalab && py.test
